# Generated by Django 4.0.3 on 2022-03-27 23:00

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['location'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(to='journey.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey.location')),
            ],
        ),
    ]
